# Generated by Django 3.0.4 on 2020-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
